repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        # releasing.md uses trailing whitespace to create hard line breaks in a
        # sample quote:
        exclude: "^doc/releasing.md$"

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: clippy
        args: ["--all-features", "--all-targets"]
      - id: fmt
